"""add AWS, GCP, Azure credentials clolumns

Revision ID: 1ad74104a4a0
Revises: 
Create Date: 2024-10-10 13:20:18.921898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad74104a4a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aws_credentials', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('gcp_credentials',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.alter_column('azure_credentials',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.drop_column('aws_access_key')
        batch_op.drop_column('aws_secret_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aws_secret_key', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('aws_access_key', sa.VARCHAR(length=150), nullable=True))
        batch_op.alter_column('azure_credentials',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('gcp_credentials',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.drop_column('aws_credentials')

    # ### end Alembic commands ###
