"""Model Update -Credential, Deployment

Revision ID: 93a4adafd58c
Revises: 1ad74104a4a0
Create Date: 2024-10-10 15:43:32.202428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a4adafd58c'
down_revision = '1ad74104a4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gcp_credentials')
        batch_op.drop_column('azure_credentials')
        batch_op.drop_column('aws_credentials')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aws_credentials', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('azure_credentials', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('gcp_credentials', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
