"""add credential_data to Credential

Revision ID: e249fef518d2
Revises: 93a4adafd58c
Create Date: 2024-10-10 16:23:58.196808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e249fef518d2'
down_revision = '93a4adafd58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credential_data', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('credential_data')

    # ### end Alembic commands ###
